### ISSUE TITLE
Attempt to install dependencies for building fails

### ISSUE THREAD

**Issue by Melab** [engine262/engine262#201]
In the project's root, I run `npm install` and I get this output on the console:

    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR!
    npm ERR! While resolving: @engine262/engine262@0.0.1                                    npm ERR! Found: @babel/core@undefined
    npm ERR! node_modules/@babel/core
    npm ERR!   dev @babel/core@"^7.18.9" from the root project
    npm ERR!                                    npm ERR! Could not resolve dependency:      npm ERR! peer @babel/core@"^7.0.0-0" from @babel/plugin-proposal-optional-chaining@7.18.9
    npm ERR! node_modules/@babel/plugin-proposal-optional-chaining
    npm ERR!   dev @babel/plugin-proposal-optional-chaining@"^7.18.9" from the root project
    npm ERR!
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR!
    npm ERR! See /data/data/com.termux/files/home/.npm/eresolve-report.txt for a full report.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-09-26T18_12_37_790Z-debug-0.log

Here are the contents of `eresolve-report.txt`:

    # npm resolution error report               
    2022-09-26T18:12:40.732Z
    
    While resolving: @engine262/engine262@0.0.1
    Found: @babel/core@undefined
    node_modules/@babel/core
      dev @babel/core@"^7.18.9" from the root project
    
    Could not resolve dependency:
    peer @babel/core@"^7.0.0-0" from @babel/plugin-proposal-optional-chaining@7.18.9
    node_modules/@babel/plugin-proposal-optional-chaining
      dev @babel/plugin-proposal-optional-chaining@"^7.18.9" from the root project
    
    Fix the upstream dependency conflict, or retry
    this command with --force, or --legacy-peer-deps
    to accept an incorrect (and potentially broken) dependency resolution.
    
    Raw JSON explanation object:
    
    {
      "code": "ERESOLVE",
      "current": {
        "name": "@babel/core",
        "errors": [
          {
            "code": "FETCH_ERROR",
            "errno": "FETCH_ERROR",
            "type": "invalid-json",
            "requiredBy": "."
          }
        ],
        "package": {},
        "whileInstalling": {
          "name": "@engine262/engine262",
          "version": "0.0.1",
          "path": "/data/data/com.termux/files/home/engine262"
        },
        "location": "node_modules/@babel/core",
        "isWorkspace": false,
        "dependents": [
          {
            "type": "dev",
            "name": "@babel/core",
            "spec": "^7.18.9",
            "error": "INVALID",
            "from": {
              "location": "/data/data/com.termux/files/home/engine262"
            }
          }
        ]
      },
      "currentEdge": {
        "type": "dev",
        "name": "@babel/core",
        "spec": "^7.18.9",
        "error": "INVALID",
        "from": {
          "location": "/data/data/com.termux/files/home/engine262"
        }
      },
      "edge": {
        "type": "peer",
        "name": "@babel/core",
        "spec": "^7.0.0-0",
        "error": "INVALID",
        "from": {
          "name": "@babel/plugin-proposal-optional-chaining",
          "version": "7.18.9",
          "whileInstalling": {
            "name": "@engine262/engine262",
            "version": "0.0.1",
            "path": "/data/data/com.termux/files/home/engine262"
          },
          "location": "node_modules/@babel/plugin-proposal-optional-chaining",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "dev",
              "name": "@babel/plugin-proposal-optional-chaining",
              "spec": "^7.18.9",
              "from": {
                "location": "/data/data/com.termux/files/home/engine262"
              }
            }
          ]
        }
      },
      "strictPeerDeps": false,
      "force": false
    }

Here are the contents of `2022-09-26T18_12_37_790Z-debug-0.log`:

    0 verbose cli /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/bin/npm                                      1 info using npm@8.19.2
    2 info using node@v18.7.0
    3 timing npm:load:whichnode Completed in 1ms
    4 timing config:load:defaults Completed in 15ms
    5 timing config:load:file:/data/data/com.termux/files/usr/lib/node_modules/npm/npmrc Completed in 18ms
    6 timing config:load:builtin Completed in 20ms                                          7 timing config:load:cli Completed in 12ms  8 timing config:load:env Completed in 4ms
    9 timing config:load:file:/data/data/com.termux/files/home/engine262/.npmrc Completed in 5ms
    10 timing config:load:project Completed in 17ms
    11 timing config:load:file:/data/data/com.termux/files/home/.npmrc Completed in 5ms
    12 timing config:load:user Completed in 8ms
    13 timing config:load:file:/data/data/com.termux/files/usr/etc/npmrc Completed in 1ms
    14 timing config:load:global Completed in 4ms
    15 timing config:load:validate Completed in 3ms
    16 timing config:load:credentials Completed in 6ms
    17 timing config:load:setEnvs Completed in 8ms
    18 timing config:load Completed in 102ms
    19 timing npm:load:configload Completed in 102ms
    20 timing npm:load:mkdirpcache Completed in 8ms
    21 timing npm:load:mkdirplogs Completed in 4ms
    22 verbose title npm install
    23 verbose argv "install"
    24 timing npm:load:setTitle Completed in 9ms
    25 timing config:load:flatten Completed in 24ms
    26 timing npm:load:display Completed in 38ms
    27 verbose logfile logs-max:10 dir:/data/data/com.termux/files/home/.npm/_logs
    28 verbose logfile /data/data/com.termux/files/home/.npm/_logs/2022-09-26T18_12_37_790Z-debug-0.log
    29 timing npm:load:logFile Completed in 43ms
    30 timing npm:load:timers Completed in 1ms
    31 timing npm:load:configScope Completed in 1ms
    32 timing npm:load Completed in 218ms
    33 timing arborist:ctor Completed in 6ms
    34 silly logfile start cleaning logs, removing 1 files
    35 silly logfile done cleaning log files
    36 timing arborist:ctor Completed in 1ms
    37 timing idealTree:init Completed in 69ms
    38 timing idealTree:userRequests Completed in 1ms
    39 silly idealTree buildDeps
    40 silly fetch manifest @babel/core@^7.18.9
    41 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 1004ms (cache updated)
    42 silly fetch manifest @babel/eslint-parser@^7.18.9
    43 http fetch GET 200 https://registry.npmjs.org/@babel%2feslint-parser 192ms (cache updated)
    44 silly fetch manifest @babel/plugin-proposal-optional-chaining@^7.18.9
    45 http fetch GET 200 https://registry.npmjs.org/@babel%2fplugin-proposal-optional-chaining 215ms (cache revalidated)
    46 silly fetch manifest @babel/core@^7.0.0-0
    47 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 274ms (cache updated)
    48 timing idealTree Completed in 1901ms
    49 timing command:install Completed in 1998ms
    50 verbose stack Error: unable to resolve dependency tree
    50 verbose stack     at [failPeerConflict] (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1381:25)
    50 verbose stack     at [loadPeerSet] (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1347:34)
    50 verbose stack     at async [buildDepStep] (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
    50 verbose stack     at async Arborist.buildIdealTree (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
    50 verbose stack     at async Promise.all (index 1)
    50 verbose stack     at async Arborist.reify (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
    50 verbose stack     at async Install.exec (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/commands/install.js:145:5)
    50 verbose stack     at async module.exports (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/cli.js:78:5)
    51 verbose cwd /data/data/com.termux/files/home/engine262
    52 verbose Linux 3.18.137-g72a7a64494e
    53 verbose node v18.7.0
    54 verbose npm  v8.19.2
    55 error code ERESOLVE
    56 error ERESOLVE unable to resolve dependency tree
    57 error
    58 error While resolving: @engine262/engine262@0.0.1
    58 error Found: @babel/core@undefined
    58 error node_modules/@babel/core
    58 error   dev @babel/core@"^7.18.9" from the root project
    58 error
    58 error Could not resolve dependency:
    58 error peer @babel/core@"^7.0.0-0" from @babel/plugin-proposal-optional-chaining@7.18.9
    58 error node_modules/@babel/plugin-proposal-optional-chaining
    58 error   dev @babel/plugin-proposal-optional-chaining@"^7.18.9" from the root project
    58 error
    58 error Fix the upstream dependency conflict, or retry
    58 error this command with --force, or --legacy-peer-deps
    58 error to accept an incorrect (and potentially broken) dependency resolution.
    58 error
    58 error See /data/data/com.termux/files/home/.npm/eresolve-report.txt for a full report.
    59 verbose exit 1
    60 timing npm Completed in 2951ms
    61 verbose unfinished npm timer reify 1664215958727
    62 verbose unfinished npm timer reify:loadTrees 1664215958797
    63 verbose unfinished npm timer idealTree:buildDeps 1664215958876
    64 verbose unfinished npm timer idealTree:#root 1664215958879
    65 verbose code 1
    66 error A complete log of this run can be found in:
    66 error     /data/data/com.termux/files/home/.npm/_logs/2022-09-26T18_12_37_790Z-debug-0.log

**Comment by Jack-Works** [comment]
closing for now. if you still have a problem, please comment!
