### ISSUE TITLE
TypeError: value.booleanValue is not a function

### ISSUE THREAD

**Issue by rwaldron** [engine262/engine262#93]
(error.js)
```js
print(true);
```

```
$ engine262 error.js
[]
/Users/rwaldron/clonez/engine262/dist/engine262.js:43577
            return value.booleanValue();
                         ^

TypeError: value.booleanValue is not a function
    at /Users/rwaldron/clonez/engine262/dist/engine262.js:43577:25
    at APIRealm.cb [as scope] (/Users/rwaldron/clonez/engine262/src/api.mjs:187:13)
    at scope (/Users/rwaldron/clonez/engine262/src/api.mjs:240:15)
    at BuiltinFunctionValue.nativeFunction (/Users/rwaldron/clonez/engine262/bin/engine262.js:49:16)
    at nativeFunction (/Users/rwaldron/clonez/engine262/src/value.mjs:273:11)
    at BuiltinFunctionValue.nativeCall [as Call] (/Users/rwaldron/clonez/engine262/src/value.mjs:320:19)
    at Call (/Users/rwaldron/clonez/engine262/src/abstract-ops/object-operations.mjs:170:13)
    at Call (/Users/rwaldron/clonez/engine262/src/runtime-semantics/CallExpression.mjs:48:17)
    at EvaluateCall.next (<anonymous>)
    at EvaluateCall (/Users/rwaldron/clonez/engine262/src/runtime-semantics/CallExpression.mjs:84:18)
```

Which is here: https://github.com/engine262/engine262/blob/7ca69bf70287e67974cb4883c2cc69e43d6e03a6/src/api.mjs#L249

Looks like it should be `return value.value.toString();`? Or `BooleanValue` needs a `booleanValue()` method.

(Strangely, this doesn't occur when `error.js` contains `console.log(true);`)

**Comment by rwaldron** [comment]
Wow. Thanks!!
